spring:
  application:
    name: expense-tracker
  cache:
    type: simple
  datasource:
    url: jdbc:h2:mem:expense-trackerDB
    username: root
    password: 123
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    open-in-view: true
    show-sql: true
    properties:
      format_sql: true
      use_sql_comments: true
      use_minimum_puts: false
      use_second_level_cache: false
      use_query_cache: false
      cache_region_factory: org.hibernate.cache.internal.NoCachingRegionFactory
    hibernate:
      ddl-auto: create-drop
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
    listener:
      concurrency: 1

server:
  shutdown: immediate
  port: 8080
  servlet:
    context-path: /expense-tracker/
app:
  alert:
    scheduler-creating: 0 0 15 * * *
    scheduler-publishing: 0 0 16 * * *